### ISSUE TITLE
Does this support colors

### ISSUE THREAD

**Issue by fcpauldiaz** [frenchtoast747/webgl-obj-loader#30]
Since mtl format is not supported I want to set a fixed color to my mesh. Would it work to create a new program with color shaders enable the attribute?

**Comment by frenchtoast747** [comment]
Yes, solid colors are possible using the meshes loaded with webgl-obj-loader.

In the [gh-pages](https://github.com/frenchtoast747/webgl-obj-loader/tree/gh-pages1) page of this project there is an [demo](https://frenchtoast747.github.io/webgl-obj-loader/) that uses this loader to load various OBJ models. One of the models that is loaded is the Blender monkey, Suzanne. While most of the other models have their texture files loaded in manually, the Suzanne model just has a solid color.

I created a helper function in this demo project, [drawObject()](https://github.com/frenchtoast747/webgl-obj-loader/blob/gh-pages/helpers.js#L1), that takes in an OBJ mesh created from this loader and draws the given mesh to the screen. There is an optional parameter, `color`, that takes in a 4 element vector that is passed in to the shader program as an attribute named `shaderProgram.modelColor`. Later on, Suzanne is drawn to the screen [here](https://github.com/frenchtoast747/webgl-obj-loader/blob/gh-pages/monkeyroom.js#L116) with the `drawObject()` function passing in a specific color (gold in this case).

You can do something similar in your own project so that you can map a solid color to your meshes.

**Comment by fcpauldiaz** [comment]
Thanks @frenchtoast747

**Comment by frenchtoast747** [comment]
You're welcome, hope that helps!
