### ISSUE TITLE
Clarify attribute indexing documentation

### ISSUE THREAD

**Issue by abcthomas** [frenchtoast747/webgl-obj-loader#60]
The current documentation around the `indicesPerMaterial` attribute is very confusing as many different terms are used interchangeably.

The Readme states that the indices can be used to index into the attribute component arrays such like
```
submeshIndices = indicesPerMaterial[0];
attributeIndex = submeshIndices[0];
vertices[attributeIndex];
normals[attributeIndex];
textures[attributeIndex];
```
However the attribute arrays themselves are flattened so that each element stores an attribute **component** rather than a vertex full attribute. Therefore to store information for a full vertex one must index the attribute arrays once for each component of the vertex attribute (so 3 times for a position and 2 times for a texture coordinate).
But it isn't clear which is the correct method of doing this either:
```
attributeIndex0 = submeshIndices[0];
attributeIndex1 = submeshIndices[1];
attributeIndex2 = submeshIndices[2];
Vector3 actualVertexPosition;
actualVertexPosition.x = vertices[attributeIndex0];
actualVertexPosition.y = vertices[attributeIndex1];
actualVertexPosition.z = vertices[attributeIndex2];
```
or
```
attributeIndex = submeshIndices[0];
Vector3 actualVertexPosition;
actualVertexPosition.x = vertices[attributeIndex];
actualVertexPosition.y = vertices[attributeIndex + 1];
actualVertexPosition.z = vertices[attributeIndex + 2];
```

I'm _guessing_ the latter otherwise it wouldn't work with attributes of different sizes, but that's just my guess. The documentation should be clearer to specify which is correct.

What also doesn't help is the naming of the `vertices` attribute which is in fact vertex positions and so should be named `positions`, but maybe I should make a separate issue for that?

**Comment by frenchtoast747** [comment]
Hi Ashleigh, thanks for your interest in this project!

You are correct, the latter example is how it works. While vertex, texture, and normal attributes are the most common for a model, it's possible that an author wants to include some other attribute whose data is of an arbitrary stride length; it's up to the initialization of the data and the shader program to determine what attributes are used and how that data is arranged.

 I've created the following diagram of a single element index that points to the parallel arrays. Do you think this would help to clarify the documentation? 
![obj loader element index description](https://user-images.githubusercontent.com/1094000/50985358-c05fda00-14c9-11e9-987b-b60ab315db00.png)

I will note that it is not intended for a user to need to directly index the model attribute arrays themselves, rather, the shader program should be doing that (although, if you would like to do some post-processing in order to derive an additional attribute, I guess this would be a way of doing that).

Lastly, the name `vertices` is used to denote the [Geometric Vertex](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Geometric_vertex). Since changing the name of the `vertices` attribute would be a breaking change, I would like to avoid that as much as possible. I wouldn't mind, however, updating the documentation to denote that it is indeed a geometric vertex attribute instead of an entire element.

**Comment by frenchtoast747** [comment]
Hi Ashleigh, thanks for your interest in this project!

You are correct, the latter example is how it works. While vertex, texture, and normal attributes are the most common for a model, it's possible that an author wants to include some other attribute whose data is of an arbitrary stride length; it's up to the initialization of the data and the shader program to determine what attributes are used and how that data is arranged.

 I've created the following diagram of a single element index that points to the parallel arrays. Do you think this would help to clarify the documentation? 
![obj loader element index description](https://user-images.githubusercontent.com/1094000/50985358-c05fda00-14c9-11e9-987b-b60ab315db00.png)

I will note that it is not intended for a user to need to directly index the model attribute arrays themselves, rather, the shader program should be doing that (although, if you would like to do some post-processing in order to derive an additional attribute, I guess this would be a way of doing that).

Lastly, the name `vertices` is used to denote the [Geometric Vertex](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Geometric_vertex). Since changing the name of the `vertices` attribute would be a breaking change, I would like to avoid that as much as possible. I wouldn't mind, however, updating the documentation to denote that it is indeed a geometric vertex attribute instead of an entire element.

**Comment by abcthomas** [comment]
I think the diagram definitely helps, but I would still add some information about how to use the indices `Mesh` provides in order to pull the correct data out of the attribute arrays that are also provided. I understand the indices are how OpenGL would index the data and that's useful as the indices can be stored and passed straight through, but it's worth clarifying that the element indices point to the *first component* in the provided attribute arrays.

I think adding the array indices of the individual attribute arrays of the above diagram would also help. Currently for instance the normal attribute array shows the XYZ components at element index 38, which is true. However if underneath it showed 0, 1, 2 etc that may go some way into clarifying how to index into the attribute arrays.

**Comment by abcthomas** [comment]
Sounds good 👍

**Comment by frenchtoast747** [comment]
Hi @abcthomas, I have updated the README based on the points from the discussion here. Could you have a quick look at it and let me know what you think?

I used the same diagram but included an additional description underneath it that should hopefully describe the boxes and why X, Y, and Z are labeled with the 38th index.
